server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    root: info
spring:
  thymeleaf:
    enabled: true
    suffix: .html
    cache: false
    servlet:
      content-type: text/html